services:
  app:
    image: digital-tolk-tms-laravel:latest
    container_name: digital-tolk-tms-laravel
    build:
      args:
        user: mirza
        uid: 1000
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - nginx
      - meilisearch
    volumes:
      - ./:/var/www
      - ./docker-compose/entrypoint.sh:/usr/local/bin/entrypoint.sh
    networks:
      - digital-tolk-tms-network

  nginx:
    image: nginx:1.17-alpine
    container_name: digital-tolk-tms-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - digital-tolk-tms-network

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: digital-tolk-tms-meilisearch
    restart: unless-stopped
    ports:
      - 7700:7700
    environment:
      MEILI_NO_ANALYTICS: 'true'
    networks:
      - digital-tolk-tms-network

networks:
  digital-tolk-tms-network:
    driver: bridge